---
- name: create swarm
  become: yes
  shell:  "docker swarm init --advertise-addr 192.168.2.20"
  register: docker_swarm_master_token_output
  ignore_errors: yes

- debug:  msg="{{docker_swarm_master_token_output.stdout}}"

- name: write swarm token output to file
  shell:  echo "{{docker_swarm_master_token_output.stdout}}" > docker_swarm_master_token_output.txt
  args:
    chdir: "{{ home_dir }}"
  
- name: store swarm command
  template:
    src: "swarm_command.j2"
    dest: "{{ home_dir }}/swarm_command.sh"
    mode: 0555

- name: extract swarm token command
  shell:  "{{ home_dir }}/swarm_command.sh"
  ignore_errors: yes
  #failed_when:  docker_swarm_join_output.stdout.find('already part of a swarm') == 1
  args:
    chdir: "{{ home_dir }}"
  register: docker_swarm_join_output
  
- name: assign to variable
  set_fact:
    docker_swarm_join_command: "{{docker_swarm_join_output.stdout}}"
    cacheable: true

- debug:  msg="{{docker_swarm_join_command}}"

#- name: promote VM-2 to docker swarm manager to be able to start jenkins slave service on VM-2
# shell:  docker node promote VM-2
