---
-   hosts:
    - masters
    vars_files:
      - ./variable_definitions/host_vars_vm1.yml
    remote_user: vagrant
    roles:
      - ssh_config
      - bashrc
      - ssh_private_key_distribution
      - docker_install
      - jenkins_master
###
-   hosts:
    - slaves
    vars_files:
      - ./variable_definitions/host_vars_vm2.yml
    remote_user: vagrant
    roles:
      - ssh_config
      - bashrc
      - ssh_private_key_distribution
      - docker_install
###
-   hosts:
    - slaves
    vars_files:
      - ./variable_definitions/host_vars_vm2.yml
    remote_user: vagrant
    roles:
      - docker_swarm_master_config
###
-   hosts:
    - masters
    vars_files:
      - ./variable_definitions/host_vars_vm1.yml
    remote_user: vagrant
    roles:
      - docker_swarm_slave_config
###
-   hosts:
    - slaves
    vars_files:
      - ./variable_definitions/host_vars_vm2.yml
    remote_user: vagrant
    roles:
      - jenkins_slave
###
###
-   hosts:
    - masters
    vars_files:
      - ./variable_definitions/host_vars_vm1.yml
    remote_user: vagrant
    roles:
      - restart_jenkins
