---
- name: add vagrant user to docker group
  become: yes
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Pull jenkins slave docker container
  shell:  docker pull jenkinsci/ssh-slave

- name: Start jenkins slave replicas within the swarm's routing mesh and re-use the authorized ssh keys from vagrant
  shell:  docker service create --name swarm-slave --publish published=2222,target=22 --replicas 4 jenkinsci/ssh-slave "$(cat /home/vagrant/.ssh/authorized_keys)"
  async:  30
  ignore_errors:  yes
