- name: install apt-transport-https
  become:   yes
  apt:
    name=apt-transport-https
    state=latest
    update_cache=yes

- name: install ca-certificates
  become:   yes
  apt:
    name=ca-certificates
    state=latest
    update_cache=yes

- name: install curl
  become:   yes
  apt:
    name=curl
    state=latest
    update_cache=yes

- name: install software-properties-common
  become:   yes
  apt:
    name=software-properties-common
    state=latest
    update_cache=yes

- name: Add GPG key
  become:   yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: store output of lsb_release
  become:   yes
  shell:  lsb_release -cs
  register: lsb_release_output
  
#- name: test print var
# shell:  echo {{lsb_release_output.stdout}} > output.txt

#- name: test grep & awk
#  become:   yes
#  shell:  ls -l | grep domain.key | awk '{print $8}'
#  register: shell_output
  
#- debug:  msg={{shell_output.stdout}}

#- name: test print 2nd var
#  shell:  echo {{shell_output.stdout}} > output2.txt

- name: add correct apt repo
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{lsb_release_output.stdout}} stable
    state: present

- name: install docker-ce
  become:   yes
  apt:
    name=docker-ce
    state=latest
    update_cache=yes

- name: install java
  become:   yes
  apt:
    name=openjdk-8-jre-headless
    state=latest
    update_cache=yes
